add table driver for DC Motor
lsd-maddrive/mishanya-bot-project pull request #22
Opened 2021-09-04 12:53 UTC by pavelrepin99

2021-09-06 20:48 UTC, KaiL4eK requested changes
Рядом с пиковым написать рабочий ток, наличие развязки и название магазина?)
+ я бы добавил в таблицу такой драйвер - выглядит неплохо http://www.elechouse.com/elechouse/index.php?main_page=product_info&products_id=2179

2021-09-08 21:27 UTC, KaiL4eK approved these changes

2021-09-09 16:03 UTC, Doraepod commented
Mosfet driver V3 это только один ключ. Использовать можно, но без реверса.
D2810 это судя по всему полумост, так что тоже без реверса.

2021-09-09 16:04 UTC, Doraepod approved these changes

2021-09-12 12:05 UTC, merged