electrical board for driver dpt
lsd-maddrive/mishanya-bot-project pull request #38
Opened 2021-10-11 19:43 UTC by pavelrepin99

2021-10-13 21:47 UTC, Doraepod commented
Я бы предложил собрать гербер файл и хранить его. Если в нем чего-то не хватает, то тогда все исходники спрятать в папку. 

Для визуальной оценки можно положить пдфку. 

И хорошо бы сделать описание с габаритами, размера монтажных отверстий и предполагаемыми электрическими элементами.

2021-10-21 22:32 UTC, Doraepod requested changes
Заархивируйте герберы и можно сливать

2021-10-22 12:50 UTC, Doraepod submitted a review, later dismissed

2021-10-24 13:13 UTC, KaiL4eK requested changes
Архивировать лучше в zip, rar - это более сложный формат для работы с ним

2021-10-30 12:15 UTC, KaiL4eK approved these changes

2021-10-30 12:16 UTC, merged