15 feature arm pwm
lsd-maddrive/mishanya-bot-project pull request #39
Opened 2021-10-13 19:27 UTC by adhelll

2021-10-16 11:11 UTC, KaiL4eK requested changes
- Сделать тест руки более управляемым (по кнопкам)
- Разбить архитектуру модуля руки на два - драйвер низкоуровневый (LLD - low level driver) и драйвер руки

2022-02-06 11:43 UTC, KaiL4eK requested changes
Выглядит неплохо, думаю, мелкие фиксы поправить и можно сливать

2022-02-06 11:43 UTC, KaiL4eK commented on firmware/README.md
> +The template runs on an STM32 Nucleo64-F411RE board.
Может все таки уже написать, что это не шаблон, а прошивка?)

2022-02-06 11:43 UTC, KaiL4eK commented on firmware/src/arm_driver.c
> +		lld_red_driver_first_direction(&control, &pwm_ch, period);
Предлагаю в перспективе перейти на отступ 2, а то код за пару вложенностей уплывает =)

2022-02-06 11:43 UTC, KaiL4eK commented on firmware/include/lld_red_driver.h
> +void lld_red_driver_first_direction(const control_driver_t *control, const pwm_channel_t *pwm_ch, uint16_t period);
А что это значит? Что такое first/second?

2022-02-06 11:43 UTC, KaiL4eK commented on firmware/src/elbow_driver.c
> +	const pwm_ctx_t left_pwm_ctx = {
еее, отступы =)

2022-02-14 07:48 UTC, serykhelena approved these changes, later dismissed

2022-02-14 19:00 UTC, serykhelena approved these changes

2022-02-14 19:22 UTC, KaiL4eK approved these changes

2022-02-14 19:22 UTC, merged