lld_control_servo
lsd-maddrive/mishanya-bot-project pull request #48
Opened 2021-11-16 15:58 UTC by pavelrepin99

2021-11-16 16:15 UTC, serykhelena requested changes

2021-11-16 16:15 UTC, serykhelena commented on firmware_767/README.md
> +The template runs on an STM32 Nucleo64-F411RE board.
Опечатка в модели СТМ

2021-11-16 16:15 UTC, serykhelena commented on firmware_767/README.md
> +### Useful links
Проверь ссылки, тоже не на ту плату

2021-11-16 16:15 UTC, serykhelena commented on firmware_767/pin_usage.md
> +#Использование модулей периферии контроллера
Нужно добавить инфу про пины для серв

2021-11-16 16:15 UTC, serykhelena commented on firmware_767/src/common.c
> +int32_t Check(int32_t duty_cycle, int32_t low,int32_t high)
Эту функцию можно заменить через define 

```c
#define CLIP_VALUE(x, min, max) ((x) < (min) ? (min) :      \
                                 (x) > (max) ? (max) : (x))
```

2021-11-16 17:56 UTC, serykhelena commented on firmware_767/openocd_server.bat
> +openocd -s "%CHIBISTUDIO%/tools/openocd/scripts" -f board/st_nucleo_f4.cfg -c "stm32f4x.cpu configure -rtos auto;"
А это зачем?

2021-11-16 20:16 UTC, KaiL4eK requested changes
В-целом, вижу готовый низкоуровневый драйвер, но без возможности использовать этот функционал в нескольких руках. 
То есть, на мой взгляд не хватает поддержки структур (контекстов) рук, в которых хранится информация о пределах каждой руки, каждого локтя, пины и т.д.
Если эта мысль не включена в эту задачу, то можно просто заметки поправить и солью

2021-11-16 20:16 UTC, KaiL4eK commented on firmware_767/include/lld_control_servo.h
> + * @args duty_cycle is raw value
Если значения сырые, то хорошо бы написать, где посмотреть пределы "от" "до"

2021-11-16 20:16 UTC, KaiL4eK commented on firmware_767/src/lld_control_servo.c
> +#define F 1000000
Комментов бы здесь, откуда взялись переменные

2021-11-16 20:16 UTC, KaiL4eK commented on firmware_767/src/lld_control_servo.c
> + * @args duty_cycle is raw value
Коменты в си файлах не обязательно дублировать из заголовков

2021-11-16 20:16 UTC, KaiL4eK commented on firmware_767/src/lld_control_servo.c
> +    duty_cycle = Check(duty_cycle,LEFT_SERVO_HAND, RIGHT_SERVO_HAND);
О, так право лево - это пределы,
Лучше назвать тогда left_pos_..._limit, right_pos_..._limit

2021-11-24 18:02 UTC, KaiL4eK commented
Комменты шик)

2021-11-24 18:15 UTC, KaiL4eK requested changes
Уже ближе к идее! Ещё чутка исправлений

2021-11-24 18:15 UTC, KaiL4eK commented on firmware_767/tests/test_lld_control_servo.c
> +        lld_control_servo_hand(duty_cycle,left_hand.left_hand_limit,
Ох ну зачем же так? Почему не передать указатель на структуру?

2021-11-24 18:15 UTC, KaiL4eK commented on firmware_767/src/lld_control_servo.c
> +void lld_control_servo_init(ioline_t line)
Интересно получается, если 4 раза вызвать с разными линиями, то инициализируется один раз?

2021-11-24 18:15 UTC, KaiL4eK commented on firmware_767/src/lld_control_servo.c
> +void lld_control_servo_init(ioline_t line)
И опять же, можно передать указатель

2021-11-24 18:15 UTC, KaiL4eK commented on firmware_767/include/lld_control_servo.h
> +static const servo_arm left_hand =
Эти штуки должны быть в с файле, а доступ к ним через более высокоуровневые функции. Типа, "установи угол левого запястья на 10 градусов". Понятно, что калибрование не проводилось, но можно коэффициент задать на глаз. А в эту верхнеуровневую функцию передать константу из перечисления (enum). Что то наподобии LEFT_WRIST, RIGHT_ARM.
Ну а для тестов из си файлов можно через external вытаскивать. В header файлы определение контекстов на кладут.

2021-11-24 18:15 UTC, KaiL4eK commented on firmware_767/include/lld_control_servo.h
> +static const servo_arm left_hand =
Эти штуки должны быть в с файле, а доступ к ним через более высокоуровневые функции. Типа, "установи угол левого запястья на 10 градусов". Понятно, что калибрование не проводилось, но можно коэффициент задать на глаз. А в эту верхнеуровневую функцию передать константу из перечисления (enum). Что то наподобии LEFT_WRIST, RIGHT_ARM. Вся эта чепушня нужна, чтобы сокрыть технически тонкости от пользователя функциями. 
Ну а для тестов из си файлов можно через external вытаскивать. В header файлы определение контекстов на кладут.

2021-11-24 19:07 UTC, serykhelena requested changes

2021-11-24 19:07 UTC, serykhelena commented on firmware_767/pin_usage.md
> +* PE9 - servo in left hand
Давай лучше в таблицу это, а не списком

2021-11-24 19:07 UTC, serykhelena commented on firmware_767/src/lld_control_servo.c
> +PWMConfig pwm1conf = {
Используй другой модуль ШИМ, любой кроме 1-го и 8-го, для них есть комплиментарный режим, это тебе пригодится для управления основанием через драйвер, который вы с Гришей сделали.

2021-11-24 19:07 UTC, serykhelena commented on firmware_767/tests/test_lld_control_servo.c
> +        lld_control_servo_hand(duty_cycle,left_hand.left_hand_limit,
Может для функции сделать только 2 аргумента: 
- duty_cycle
- указатель на структуру 

А внутри функции уже дёргать поля структуры?

2021-11-24 19:07 UTC, serykhelena commented on firmware_767/tests/test_lld_control_servo.c
> +void test_lld_servo_left_wrist(void)
Может сделать одну функцию, но в аргумент к функции передавать указатель на структуру? 
То есть из main для каждого теста будет меняться только аргумент, но не название функции

2021-12-02 09:06 UTC, serykhelena requested changes

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/include/lld_control_servo.h
> +#include <common.h>
В заголовочнике здесь, не обязательно включать `common`. Можно это сделать прямо в с-файле теста `test_lld_control_servo.c `

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/include/test.h
> +#include <common.h>
В заголовочнике здесь, не обязательно включать `common`. Можно это сделать прямо в с-файле теста `test_lld_control_servo.c `

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/src/main.c
> +
Сюда уже добавить `#include "common.h"`

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/tests/test_lld_control_servo.c
> +
Сюда уже добавить `#include "common.h"`

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/include/lld_control_servo.h
> +extern servo_arm right_wrist;
Мне всё ещё не нравится как-то, что в заголовочнике через extern открывают не read-only структуры. Появилась идея, что если в lld_servo.c добавить функцию обёртку, которая как аргумент будет принимать enum значение, типа LEFT_HAND, LEFT_WRIST, etc. И по switch будет дёргать тот указатель на структуру, который нужно. Тогда сами объекты структур не нужно будет таскать во вне из с-файла. Только в common, наверное, положить enum. И в тестах уже его использовать. При необходимости можно ещё сделать функцию `servo_t* getServoPtr(int key)`, чтобы по ENUM значению получать указатель на структуру

2021-12-02 09:06 UTC, serykhelena commented on firmware_767/src/main.c
> +        test_lld_servo_left_hand(&left_wrist);
Тесты нужно на все сервы сделать, не только на left_hand

2021-12-02 19:05 UTC, KaiL4eK commented on firmware_767/src/main.c
> +        test_lld_servo_left_hand(&left_wrist);
Чет мне кажется, что рутины тестов не должны принимать аргументов вообще. Есть в названии фигурирует конкретика (левая рука), то передавать аргумент не стоит, а сделать N тестов - каждый со своим названием. Альтернативно, можно обобщить название теста и передавать структуру.
Но главное, не полируйте все до идеала - все равно всегда есть факт все нафиг перерефакторить, поэтому стоит сейчас сделать какой-то вариант, а потом уже смотреть, как идет.

2021-12-02 19:07 UTC, KaiL4eK approved these changes, later dismissed

2022-01-24 19:19 UTC, serykhelena requested changes

2022-01-24 19:19 UTC, serykhelena commented on firmware_767/src/lld_control_servo.c
> +void setServoPtr(int16_t duty_cycle, int8_t servo_t)
переименуй, пожалуйста, функцию, чтобы было `lld_set_dutycycle_servo` (или ещё как-то) - чтобы все функции были в одном стиле, а то у тебя до этого был змеиный стиль, а тут верблюд (=

2022-01-24 19:19 UTC, serykhelena commented on firmware_767/src/main.c
> +        test_lld_servo(RIGHT_HAND);
А давай сюда добавишь дефайны для каждой сервы, то есть у тебя будут дефайны для каждой сервы ... test_lld_servo(LEFT_HAND), test_lld_servo(RIGHT_WRIST)  и т.д. Чтобы только в одном месте поменять код, а в исходники уже не соваться (=

2022-01-24 19:23 UTC, serykhelena commented on firmware_767/src/lld_control_servo.c
> +void setServoPtr(int16_t duty_cycle, int8_t servo_t)
И у servo_t похоже тип должен быть typo_servo

2022-01-26 07:01 UTC, serykhelena approved these changes

2022-01-26 07:40 UTC, merged