16 feature close arm sys
lsd-maddrive/mishanya-bot-project pull request #60
Opened 2022-02-19 22:54 UTC by adhelll

2022-02-21 19:29 UTC, serykhelena requested changes

2022-02-21 19:29 UTC, serykhelena commented on firmware/include/PID.h
> +
Зону насыщения для интегральной и dead zone для пропорциональной частей не хочешь сразу заложить в структурах?

2022-02-21 19:29 UTC, serykhelena commented on firmware/include/common.h
> +#define PROGRAM_TEST_CLOSE_SYS 3
в названии бы указать, что это СУ для руки

2022-02-21 19:29 UTC, serykhelena commented on firmware/include/encoder.h
> +/************ Status bita ************/
Опечатка `bitA`

2022-02-21 19:29 UTC, serykhelena commented on firmware/src/close_sys_arm.c
> +	PID->error.prev_P = 0;
Может сделать отдельную функция для сброса регулятора?

2022-02-21 19:29 UTC, serykhelena commented on firmware/src/close_sys_arm.c
> +	while(1)
мне кажется, этот цикл/расчёт регулятора можно сделать в отдельном потоке

2022-02-26 22:17 UTC, KaiL4eK requested changes

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/close_sys_arm.c
> +	while(1)
я так понимаю, можно в отдельном потоке просто вызвать эту функцию

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/close_sys_arm.c
> +			arm_angle->zero_cross = true;
а для чего этот флаг?

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/close_sys_arm.c
> +static void normalize_interval (float min_angle, float max_angle, normalize_angle_t *arm_angle)
я бы написал мелкие тесты, которые можно просто запустить и проверить (по аналогии концепции unit-тестирования). То есть, проверить на разных входных данных, что функция работает

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/close_sys_arm.c
> +static double normalize_angle (float min_angle, normalize_angle_t *arm_angle)
аналогично, на эту функцию тестиков бы с разными входами

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/close_sys_arm.c
> +	if(err_reg->P<0)
а это зачем? почему при отрицательном разворачиваем? это вроде правильно математикой покрывается

2022-02-26 22:17 UTC, KaiL4eK commented on firmware/src/encoder.c
>  void Encoder_init(void)
Аналогично драйверам и движкам, контекст для энкодера не хочется сделать?

2022-02-27 09:10 UTC, adhelll commented on firmware/src/close_sys_arm.c
> +			arm_angle->zero_cross = true;
Если диапазон изменения углов энкодера, например, от 350 до 30, то есть будет переход через 0 при повороте руки, то перевод текущего угла будет по-другому рассчитываться

`static double normalize_angle (float min_angle, normalize_angle_t *arm_angle)
{

	double current_angle = Encoder_Read();

	if(arm_angle->zero_cross)
	{
		if((current_angle+arm_angle->shift)>=360)
			current_angle = current_angle - min_angle;

		else
			current_angle = current_angle + arm_angle->shift;
	}
	else
		current_angle = current_angle - arm_angle->shift;

	return current_angle;

}`

2022-02-27 09:12 UTC, adhelll commented on firmware/src/encoder.c
>  void Encoder_init(void)
оке, тогда модуль для энкодера я доделаю, думал, что кто-то другой этим будет заниматься

2022-02-27 09:18 UTC, adhelll commented on firmware/src/close_sys_arm.c
> +	if(err_reg->P<0)
это было бы верно, если бы была обработка отрицательной скважности, я разбил управление для рук на две функции (вверх/вниз), поэтому только положительную скважность рассматриваю

2022-02-27 09:22 UTC, adhelll commented on firmware/src/close_sys_arm.c
> +	if(err_reg->P<0)
хотя я бы это переделал

2022-03-25 17:49 UTC, KaiL4eK requested changes

2022-03-25 17:49 UTC, KaiL4eK commented on firmware/Makefile
> +CHIBIOS  := D:/RTOS/ChibiStudio20v0/chibios203
Не надо так

2022-03-25 17:49 UTC, KaiL4eK commented on firmware/include/arm_driver.h
> +  BB = 0,								                        // this type of driver requires two channel PWM
Слушай, ну что-то надо сделать, а то совсем все едет

2022-03-25 17:49 UTC, KaiL4eK commented on firmware/include/arm_driver.h
>  #ifndef INCLUDE_ARM_DRIVER_H
Так файл и не переименовал?)

2022-03-25 17:49 UTC, KaiL4eK commented on firmware/tests/test_arm_control_system.c
> +  time = chThdSleepUntilWindowed(time, TIME_MS2I(20)+time);
вылезло как-то, должно быть внутри while

2022-03-28 15:46 UTC, KaiL4eK approved these changes

2022-03-28 15:47 UTC, merged