[WIP] 52 check driver
lsd-maddrive/mishanya-bot-project pull request #64
Opened 2022-03-18 14:43 UTC by pavelrepin99

2022-03-19 11:48 UTC, serykhelena requested changes

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/include/common.h
> +#define MAIN_PROGRAM PROGRAM_TEST_BB_DRIVER
Давай в название теста больше конкретики, например, PROGRAM_TEST_BASE_WHEEL_1
И после, будет ещё 2 теста, на оставшиеся колёса (можно сделать также как с сервой, задавать в аргументе теста, какое колесо крутить)

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/include/lld_bridge_system.h
> +  PWMDriver 		    *driver_ptr;	              // PWM pointer
Что-то отступы колбасит

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/include/lld_bridge_system.h
> +  ioline_t 			    PWM_2;			                // second digit pin
опечатка в комментарии

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/include/lld_bridge_system.h
> +  pwm_channel_t     pwm_ch;			                // typedef (search for description in this file)
давай сюда краткое описание добавим, лезть в description-file бывает лениво

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/src/lld_bb_driver.c
> +	pwmEnableChannel(control->pwm_setting_ctx.driver_ptr, pwm_ch->ch_pwm_1, period);
проверь отступы

2022-03-19 11:48 UTC, serykhelena commented on firmware_767/tests/test_lld_bb_driver.c
> +const control_driver_t test_control_bb = {
Этих структур не надо в файле теста, они скорее внутренние. Давай сделаем наподобие с сервами, структуру на каждый движок/колесо, который будет содержать пределы управления, и может туда же засунуть какой модуль ШИМ используется. А наружу enum выплюнем

2022-03-22 18:34 UTC, Muzalevsky commented on firmware_767/include/lld_bb_driver.h
> +void lld_bb_driver_reverse(const control_driver_t *control, const pwm_channel_t *pwm_ch, uint16_t period);
Если я что-то понимаю, то здесь две одинаковые функции.
Может переименовать `direct` в `forward`? А потом сделать обёртку, в которую аргументом передать направление?
`lld_bb_driver_direct/lld_bb_driver_reverse`

2022-03-22 18:34 UTC, Muzalevsky commented on firmware_767/include/lld_bridge_system.h
> +  uint8_t           alt_func_2;					        // PWM second channel alternative function number
Может быть сделать `enum `для `alt_func_*` ? Я не могу понять что значит `alt_func_1 = 1` в [тут](https://github.com/lsd-maddrive/mishanya-bot-project/pull/64/files#diff-8eed0c229565b96849cd5461827f1408c8c7dccd93aa26019706d1be1413f566R18)

2022-03-22 20:03 UTC, serykhelena commented
1. В src/headers нужно создать новые файлы lld_conrol_wheel.c/lld_conrol_wheel.h 
2. Внутри lld_conrol_wheel.c жёстко используем функционал bb_driver.c 
3. Пины для 1-го колеса (PWM 1)
MOTOR1_PWM_LINE_HIN1 PAL_LINE(GPIOE, 11)
MOTOR1_PWM_LINE_LIN1 PAL_LINE(GPIOE, 10)
MOTOR1_PWM_LINE_HIN2 PAL_LINE(GPIOE, 13)
MOTOR1_PWM_LINE_LIN2 PAL_LINE(GPIOE, 12)

Эти пины можно положить внутрь структуры, которая описывает колёсо 
Изменения из bb_driver - убрать, обёртка над драйвером будет в lld_conrol_wheel

4. в функции lld_control_servo_init дёргаем функцию init из bb_driver с нужными аргументами 
5. Аналогично, делаем обёртку для direct/reverse и т.д. 
То есть нужны функции (примерно) 
- lld_conrol_motor_init( void ) - в этой функции можно прямо все колёса сразу инициализировать
- lld_control_set_raw_motor_power( motorNumberValue_t motor_num, uint32_t duty, lldMotorDirection_t dir )
- lld_control_set_motor_power( motorNumberValue_t motor_num, lldControlValue_t inputPrc ) - -100% полный назад, 100% - полный вперёд 
- lld_control_stop_all_motors( void )

2022-10-22 10:36 UTC, serykhelena commented
Мир изменился, код в ветке сильно устарел

2022-10-22 10:36 UTC, closed without merging