77 feature arm trajectory
lsd-maddrive/mishanya-bot-project pull request #94
Opened 2022-11-09 12:48 UTC by adhelll

2022-11-11 16:27 UTC, KaiL4eK requested changes
Выглядит круто, есть опечатка, как-то проверялась работа логики?

2022-11-11 16:27 UTC, KaiL4eK commented on firmware/Torse/src/arm_kinematic.c
> +  sin_angles->th1 = sinf(angles->th1);
Не опечатка ли?

2022-11-11 16:27 UTC, KaiL4eK commented on firmware/Torse/todo_list.md
> +Что необходимо сделать:
Может это в виде issues, сразу можно будет туда мысли накидывать

2022-11-13 17:27 UTC, adhelll commented on firmware/Torse/todo_list.md
> +Что необходимо сделать:
Закину в issues

2022-11-13 17:30 UTC, adhelll commented on firmware/Torse/src/arm_kinematic.c
> +  sin_angles->th1 = sinf(angles->th1);
Да, опечатка, эта функцию только в прямой задаче используется, поэтому не заметил

2022-11-13 17:31 UTC, adhelll commented
> Выглядит круто, есть опечатка, как-то проверялась работа логики?

Функцию прямой задачи дополнительно протестирую, обратную задачу проверял на матлаб модели

2022-11-20 17:14 UTC, adhelll commented
Проверил прямую кинематику, исправил опечатку, можно мерджить

2022-11-20 19:15 UTC, KaiL4eK approved these changes

2022-11-20 19:15 UTC, merged